version: '3.9'

services:
  web:
    build: .
    command: python /quiz/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/quiz
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-jeneh@7stg_o$$$$4ec74)p45-g30(!(g-#@22_ei5ova4781yja"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:


