# Generated by Django 4.0.7 on 2022-09-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(default=50, help_text='Required score in %'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='resolution_time',
            field=models.PositiveIntegerField(default=15, help_text='Quiz Duration in minutes'),
        ),
    ]
